"""Add missing asset columns

Revision ID: c06fb0872fe4
Revises: 
Create Date: 2025-08-13 16:20:55.222434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06fb0872fe4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('transaction_date', sa.Date(), nullable=True))
    op.add_column('assets', sa.Column('transaction_type', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('received_from', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('purpose', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('issued_by', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('received_by', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('expected_return_date', sa.Date(), nullable=True))
    op.add_column('assets', sa.Column('is_received', sa.Boolean(), nullable=True))
    op.drop_column('assets', 'employee_number')
    op.drop_column('assets', 'current_location')
    op.drop_column('assets', 'asset_issued_to')
    op.drop_column('assets', 'date_of_issue')
    op.alter_column('challan_items', 'asset_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_challan_items_id'), 'challan_items', ['id'], unique=False)
    op.create_index(op.f('ix_challans_id'), 'challans', ['id'], unique=False)
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.alter_column('locations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.alter_column('locations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_challans_id'), table_name='challans')
    op.drop_index(op.f('ix_challan_items_id'), table_name='challan_items')
    op.alter_column('challan_items', 'asset_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('assets', sa.Column('date_of_issue', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('asset_issued_to', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('current_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('employee_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('assets', 'is_received')
    op.drop_column('assets', 'expected_return_date')
    op.drop_column('assets', 'received_by')
    op.drop_column('assets', 'issued_by')
    op.drop_column('assets', 'purpose')
    op.drop_column('assets', 'received_from')
    op.drop_column('assets', 'transaction_type')
    op.drop_column('assets', 'transaction_date')
    # ### end Alembic commands ###
